/** Section 13 — SEO, Metadata & Social. */

import { profile } from "./profile";

export const seo = {
  title: "Shivam Sharma — Associate Product Manager · AI Products",
  titleTemplate: "%s — Shivam Sharma",
  description:
    "Builder-PM working on AI-first products. I run discovery, write the PRD, then ship it — React, Electron and LLM integrations. Led a 10-person build, delivered for a paying client, shipped a platform that processed 4,000+ submissions.",
  ogTitle: "Shivam Sharma — I write the PRD, then I ship it",
  ogDescription:
    "Builder-PM on AI-first products. Discovery and PRDs through hands-on development in React, Electron and LLM integrations. Led a 10-person build, delivered for a paying client, shipped a platform that processed 4,000+ submissions in live use.",
  ogImageAlt: "Shivam Sharma — Associate Product Manager, AI Products",
  siteName: "Shivam Sharma — Portfolio",
  twitterDescription:
    "Builder-PM on AI-first products. Four products built end to end: a voice-first AI desktop companion, a paid client marketplace, and a platform that processed 4,000+ submissions.",
  keywords: [
    "associate product manager",
    "technical product manager",
    "AI product manager",
    "builder PM",
    "product manager who codes",
    "AI product management",
    "associate product manager fresher",
    "technical product manager India",
    "APM 2026",
    "entry level product manager AI",
    "product manager intern India",
    "technical PM candidate",
    "product discovery",
    "PRD authoring",
    "RICE prioritization",
    "roadmapping",
    "user stories",
    "acceptance criteria",
    "MVP definition",
    "KPI definition",
    "stakeholder management",
    "agile",
    "scrum",
    "LLM integration",
    "prompt engineering",
    "AI workflow design",
    "voice interfaces",
    "context-aware systems",
    "SQL",
    "Python",
    "pandas",
    "Metabase",
    "Mixpanel",
    "funnel analysis",
    "cohort analysis",
    "retention analysis",
    "A/B testing",
    "exploratory data analysis",
    "React",
    "Next.js",
    "TypeScript",
    "Electron",
    "Supabase",
    "Prisma",
    "REST APIs",
    "Git",
    "Jira",
    "Notion",
    "Shivam Sharma product manager",
    "CuteHelper",
    "UrbanIQ",
    "ServiceHub",
    "Docmize",
    "Groq Whisper",
    "LLaMA 4 Scout",
    "I.K. Gujral Punjab Technical University",
    "Google Project Management Professional Certificate",
    "product manager with engineering background",
    "PM who can write code",
    "AI-first product manager portfolio",
    "product manager case study portfolio",
    "technical product manager fresher India",
    "voice-first AI desktop app",
    "product manager Gurugram Haryana",
  ],
} as const;

/** Person schema. Google surfaces jobTitle and knowsAbout in knowledge panels. */
export const personSchema = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Shivam Sharma",
  jobTitle: "Associate Product Manager, AI Products",
  description:
    "Builder-PM working on AI-first products — discovery and PRDs through hands-on development, then instrumentation.",
  url: profile.siteUrl,
  email: `mailto:${profile.email}`,
  telephone: "+918360900804",
  address: {
    "@type": "PostalAddress",
    addressLocality: "Gurugram",
    addressRegion: "Haryana",
    addressCountry: "IN",
  },
  alumniOf: {
    "@type": "CollegeOrUniversity",
    name: "I.K. Gujral Punjab Technical University",
  },
  knowsAbout: [
    "Product Management",
    "Product Discovery",
    "PRD Authoring",
    "RICE Prioritization",
    "LLM Integration",
    "Prompt Engineering",
    "React",
    "Next.js",
    "TypeScript",
    "Electron",
    "SQL",
    "Python",
  ],
  sameAs: [profile.links.github, profile.links.linkedin],
} as const;

/** OG image direction: type only, near-black, one hairline rule. */
export const ogImage = {
  name: "SHIVAM SHARMA",
  headline: ["I write the PRD,", "then I ship it."],
  proof: [
    "4 products · 10-person team led ·",
    "4,000+ submissions in live use ·",
    "1 paying client",
  ],
} as const;
